/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AtskaHeart (https://sketchfab.com/atskaheart)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pixel-car-1bb69bbe51fc4e11ad10ea80c32ca7f6
title: Pixel car
*/

import * as THREE from 'three'
import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_9: THREE.Mesh
    Object_7: THREE.Mesh
    Object_11: THREE.Mesh
    Object_15: THREE.Mesh
    Object_13: THREE.Mesh
    Object_5: THREE.Mesh
    Object_19: THREE.Mesh
    Object_17: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_37: THREE.Mesh
    Object_35: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    TexturePaint: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Animation'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function PixelCar({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/pixel_car/scene.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)

  useLayoutEffect(() => {
    actions?.Animation.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.03, 0.48]}>
            <group position={[-0.7, 1.49, 0.17]}>
              <group position={[0, -0.03, 0]}>
                <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
              </group>
              <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
            </group>
            <group position={[0, 1.48, 0.06]}>
              <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
            </group>
            <group position={[-0.75, 0.91, 1.02]}>
              <group position={[0.08, 0.35, -0.11]}>
                <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
              </group>
              <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
            </group>
            <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
          </group>
          <group position={[0.75, 1.52, 0.64]}>
            <group position={[0, -0.03, 0]}>
              <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
            </group>
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
          </group>
          <group position={[0.61, 0.3, -0.24]} rotation={[0.5, 0, 0]}>
            <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
          </group>
          <group position={[-0.61, 0.3, -0.24]} rotation={[0.5, 0, 0]}>
            <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
          </group>
          <group position={[0.17, 1.57, -0.33]} rotation={[3.14, 0.39, -3.14]}>
            <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
          </group>
          <group position={[0.4, 0.92, 1.23]} rotation={[0, 0, 0]}>
            <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
          </group>
          <group position={[0, 1.01, 1.59]} rotation={[-Math.PI, 0.39, -Math.PI]}>
            <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
          </group>
          <group position={[0, 1.39, 1.21]} rotation={[-3.14, 0.39, 3.14]}>
            <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
          </group>
          <group position={[0, 0.43, 2.27]} rotation={[-Math.PI, 0.39, -Math.PI]}>
            <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
          </group>
          <group position={[0.75, 0.94, 1.5]}>
            <group position={[-0.08, 0.35, -0.11]}>
              <mesh geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
            </group>
            <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
          </group>
          <group position={[0.61, 0.3, 1.78]} rotation={[0.5, 0, 0]}>
            <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
          </group>
          <group position={[-0.61, 0.3, 1.78]} rotation={[0.5, 0, 0]}>
            <mesh geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pixel_car/scene.gltf')
